# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1 # Use 2.1 to enable using orbs and other features.

# Declare the orbs that we'll use in our config.
# read more about orbs: https://circleci.com/docs/2.0/using-orbs/
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  test:
    parameters:
      ruby-version:
        type: string
      bundler-version:
        type: string
    docker:
      # specify the version you desire here
      - image: cimg/ruby:<< parameters.ruby-version >>
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: << parameters.bundler-version >>
          with-cache: true
      - ruby/rspec-test

workflows:
  build_and_test:
    jobs:
      - test:
          # matrix jobs https://circleci.com/blog/circleci-matrix-jobs/
          matrix:
            parameters:
              ruby-version: ["2.5", "2.7"]
              bundler-version: ["1.17.3", "2.2.3"]
